rakutentech/js-miniapp

- js-miniapp-sample/package.json
- js-miniapp-sdk/README.md
- js-miniapp-sdk/package.json
Add changelog for 1.0.0 release.
> docs: (sdk) Update changelog for v1.0.0

- js-miniapp-bridge/src/bridge.js
JS Bridge changes to request any permissions for Android/iOS SDK
- [MINI-914](https://jira.rakuten-it.com/jira/browse/MINI-914)
- [MINI-915](https://jira.rakuten-it.com/jira/browse/MINI-915)
> JS bridge changes to request permission from the SDK

- js-miniapp-bridge/package.json
- js-miniapp-sdk/package.json
Update versions for alpha release for gurunavi
> Update versions for alpha release

- .github/CODEOWNERS
Add new team member to code owners.
> chore: Add @khairul-alam-licon to code owners

- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/README.md
Update docs for 1.2.0 release
[MINI-1254](https://jira.rakuten-it.com/jira/browse/MINI-1254?src=confmacro)
> update changelog for 1.2.0 release

- README.md
Also added badges for NPM an CircleCI
> docs: Add CI information to readme

- js-miniapp-bridge/src/bridge.js
Override `navigator.geolocation.getCurrentPosition` for iOS SDK
> Geolocation override changes for iOS SDK

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-bridge/test/test.spec.ts
Added load rewarded ad functionality
Added show rewarded ad functionality
Added new unit tests
Updated unit tests
> bridge: Functionality to load and show rewarded ads.

- .github/CODEOWNERS
Add Abhijit-majumder to code owners
> Add Abhijit-majumder to code owners

- js-miniapp-bridge/src/android/android-bridge.ts
- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-bridge/src/ios/ios-bridge.ts
- js-miniapp-bridge/src/types/platform.ts
- js-miniapp-bridge/test/test.spec.ts
- js-miniapp-sdk/README.md
- js-miniapp-sdk/src/index.ts
- js-miniapp-sdk/src/miniapp.ts
- js-miniapp-sdk/src/types/responseTypes/index.ts
- js-miniapp-sdk/src/types/responseTypes/interstitial/index.ts
- js-miniapp-sdk/src/types/responseTypes/rewarded/index.ts
- js-miniapp-sdk/test/miniapp.spec.ts
SDK:
- Update the response type of ads to string, Reward.
- Device OS detection. The value could be `Android`, `iOS` or `Unknown`.
Bridge:
- Update the response type of ads to string, Reward.
- Platform detection. The value could be `Android` or `iOS`.
> refactor: admob

- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/README.md
Merging changelog for v1.2.0 to master.
> Merge 1.2.0 changelog to master

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-sample/src/services/user/actions.js
- js-miniapp-sdk/README.md
- js-miniapp-sdk/src/miniapp.ts
- js-miniapp-sdk/test/miniapp.spec.ts
* Bridging script changes to retrieve UserName and ProfilePhoto
* JS-SDK script changes to retrieve UserName and ProfilePhoto
* js-sdk-sample app changes to retrieve and display the user details
> Retrieve Username and Profile photo

- js-miniapp-sample/src/pages/share.js
- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/README.md
Updated a few missed documentation for User Details retrieval
> Updated documentation for User Details

- js-miniapp-sample/src/pages/landing.js
- js-miniapp-sample/src/pages/tests/landing.test.js
Update the sample app for Platform detection.
MINI-1798
> sample: platform detection

- js-miniapp-sample/external-webview/index.html
- js-miniapp-sample/src/pages/ads.js
- js-miniapp-sample/src/pages/uri-schemes.js
- sample: (ads) Add input fields and 'load' buttons
- This is needed so all test cases can be covered in QA
- sample: (uri) Add external webview page with tel and _blank links
- This HTML file is accessed via the raw github url.
> Sample app updates for QA testability

- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/README.md
- js-miniapp-sdk/package.json
- js-miniapp-sdk/src/index.ts
- js-miniapp-sdk/src/miniapp.ts
- js-miniapp-sdk/test/miniapp.spec.ts
Note: This is being merged into the `release/1.3.0` branch.
- refactor (sdk) Remove screen orientation interface
- This won't be included in the 1.3.0 release, but will be included in the next release
- docs: (sdk) Update changelog for v1.3.0
> Release preparation for SDK v1.3.0

- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/README.md
- js-miniapp-sdk/package.json
Merging the changelog updates from the 1.3.0 release.
> Mege changelog updates from release branch to master

- js-miniapp-sdk/package.json
- yarn.lock
Added tinyify to minify this bundle. This removes some code that was being inlcuded which was not needed such as MiniAppBridge
> build: (sdk) Minify the js bundle miniapp.bundle.js

- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/package.json
Update changelog date and version in package.json.
> 1.4.0 release updates

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-bridge/src/index.ts
- js-miniapp-bridge/src/types/token-data.ts
- js-miniapp-sample/src/js_sdk/index.js
- js-miniapp-sample/src/pages/auth-token.js
- js-miniapp-sample/src/pages/tests/auth-token.test.js
- js-miniapp-sample/src/pages/tests/fetch-credentials.test.js
- js-miniapp-sdk/src/index.ts
- js-miniapp-sdk/src/miniapp.ts
- js-miniapp-sdk/test/miniapp.spec.ts
- Get access token from hostapp as `TokenData` object
- Update the authentication mobile section to demo this feature: Display token and expiration date.
Note: As a discussion, the user permission for access token will be implemented when first time permission is done.
MINI-1865
> feature: retrieve access token

- .circleci/config.yml
- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/README.md
- js-miniapp-sdk/package.json
Update changelog and user guide.
> Release preparation for v1.5.0

- js-miniapp-sample/src/pages/media.js
On the "Media" screen, I've added button to show an autoplaying, fullscreen video.
> feat: (sample) Add autoplay fullscreen video

- js-miniapp-sdk/README.md
Added troubleshooting about a common error case.
> docs: Add troubleshooting section with 'undefined' error

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-bridge/src/index.ts
- js-miniapp-bridge/src/types/contact.ts
- js-miniapp-sample/src/pages/user-details.js
- js-miniapp-sample/src/services/user/actions.js
- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/README.md
- js-miniapp-sdk/src/index.ts
- js-miniapp-sdk/src/miniapp.ts
- js-miniapp-sdk/test/miniapp.spec.ts
SDK & Bridge:
- Add Contact model.
- Add `getContact()` method.
- Cleanup document & unit test.
Sample app:
- Get and display contact list.
MINI-2297
> feature: get contacts

- js-miniapp-sdk/src/miniapp.ts
Stop using local bridge variable to avoid early injection.
MINI-2148
> refactor: change bridge call

- js-miniapp-sdk/package.json
Update to latest version v1.6.1.
> build: package v1.6.1

- .github/workflows/codeql-analysis.yml
See here: https://github.blog/2020-09-30-code-scanning-is-now-available/
I tested this in my fork: https://github.com/corycaywood/js-miniapp/actions/runs/526364622
> ci: Add Github Action for CodeQL security analysis

- js-miniapp-sample/src/index.css
- js-miniapp-sample/src/pages/landing.js
This fixes an issue where the platform and parameter info on the home screen were wrapping to the next line in a random spot. Also fixes an issue where the iOS App could scroll the entire App shell.
> fix: (sample) Fixed iOS issues with CSS

- js-miniapp-sdk/README.md
Some users were confused about how to use custom vs device permissions, so this tries to clarify that.
> docs: Update permissions section in user guide

- js-miniapp-sample/src/components/tests/ToolBar.test.js
- js-miniapp-sdk/README.md
- The description of manifest in miniapp.
- Explain the usage for required and optional permission in permission request.
- Remove duplicated block in testcase.
MINI-2838
> doc: miniapp manifest

- js-miniapp-sample/public/manifest.json
- js-miniapp-sdk/README.md
Update the js sample app with metadata in manifest.json.
It is also related to this [PR](https://github.com/rakutentech/js-miniapp/pull/106).
> sample: add metadata in manifest

- js-miniapp-sample/src/pages/landing.js
A small change in JS SDK Sample app displaying query params.
**INPUT 1:** <URL>/index.html?exampleKey=exampleValue#exampleFragment
**Query Parameters:** exampleKey=exampleValue
**URL Fragment:** exampleFragment
**INPUT 2:** <URL>/index.html?exampleKey=exampleValue#
**Query Parameters:** exampleKey=exampleValue
**URL Fragment:** None
MINI-2828
> Updated sample app to display query params detailed

- js-miniapp-bridge/src/types/contact.ts
- js-miniapp-sample/src/pages/user-details.js
- js-miniapp-sdk/CHANGELOG.md
* Display Name & Email in the Contact list screen.
* For old Contacts which has only ID - Name & Email will not be displayed.
MINI-2914
> Display Name & Email in Contact list

- js-miniapp-bridge/src/types/contact.ts
Name and e-mail fields should be optional because they might not be set by the Host App.
> Make contact name and e-mail fields optional

- js-miniapp-sample/src/hooks/useGeoLocation.js
Clear previous error state when requesting location permission.
MINI-3043
> sample: fix location watching state

- js-miniapp-sample/public/manifest.json
Add example meta data which can be used for an "Approval" screen before downloading a mini app.
> sample: Add example meta-data to manifest.json

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-sdk/src/modules/chat-service.ts
- js-miniapp-sdk/test/miniapp.spec.ts
Bridge & SDK: Support send message to multiple contacts.
@khairul-alam-licon @Climbatize 
Please take a note that the return of success from android/ios sdk is a json string of list of contact id.
MINI-2472
> bridge & sdk: send a message to multiple contacts

- js-miniapp-sample/src/pages/message.js
- Catch error when get onError from android/ios.
- Max line for text input to not cover action button when it is a long text.
MINI-3089
> refactor: sample send message

- js-miniapp-sample/external-webview/index.html
- js-miniapp-sample/src/pages/uri-schemes.js
Add `mailto` to sample app and external test page.
MINI-2788
> sample: mailto

- js-miniapp-sample/public/manifest.json
Change the key names for meta-data.
> fix: (sample) Change key names for manifst customMetaData

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-bridge/src/types/custom-permissions.ts
- js-miniapp-sample/public/manifest.json
- js-miniapp-sample/src/services/message/actions.js
- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/README.md
- Add send message permission to bridge.
- Request send message permission before sending message in sample app.
MINI-3193
> feat: send message permission

- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/package.json
> release v1.9.0

- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/package.json
> release v1.10.0

- js-miniapp-sample/src/pages/file-upload.js
- js-miniapp-sample/src/pages/tests/file-upload.test.js
Added general, images, pdf buttons to upload file types accordingly.
MINI-3346
> [MINI-3346] Add Buttons for different file types

- js-miniapp-bridge/test/test.spec.ts
> improved bridge tests coverage to 87%

- js-miniapp-sample/src/pages/message.js
- js-miniapp-sample/src/services/message/actions.js
- js-miniapp-sample/src/services/message/reducers.js
- js-miniapp-sample/src/services/message/types.js
QA was confused not seeing the banner message when sending a message to single contact id. I removed the banner message field so there is no more confusion
MINI-3476
> [MINI-3476] removed banner field from single contact id screen

- js-miniapp-sample/src/pages/uri-schemes.js
This allows the callback URL to be changed if the mini app is being used in a different Host App
> feat: (sample) Add callback url field to URI screen

- js-miniapp-sample/src/pages/user-details.js
- js-miniapp-sample/src/services/permissions/reducers.js
Fix the wrong info when fetching user details and points. There  should be no dependency between these two features and wrong error message should not be seen if permission is already granted.
- MINI-3522
> sample app ui fix: user details and points show wrong UI info 

- js-miniapp-sample/src/pages/user-details.js
- js-miniapp-sample/src/services/permissions/reducers.js
Permission state was not updating if changed to "Denied" while the mini app is still running.
MALI-637
> fix: (sample) Denied permission state was not updating at runtime

- js-miniapp-sample/src/pages/file-download.js
Added permission check before downloading files.
MINI-4291
> [MINI-4291] Added permission check before downloading files

- js-miniapp-bridge/package.json
- js-miniapp-sample/package.json
- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/package.json
Changes needed to continue with the release v1.12.0
> Release v1.12.0 changes

- js-miniapp-bridge/src/types/host-environment-info.ts
- js-miniapp-sample/src/pages/landing.js
added hostLocale variable to HostEnvironmentInfo
[MINI-4413]
> [MINI-4413]added hostLocale variable to HostEnvironmentInfo

- js-miniapp-sample/src/pages/message.js
Added default values specific to each message type
[MINI-4420]
> [MINI-4420] Added default values specific to each message type

- js-miniapp-sample/README.md
- js-miniapp-sample/src/pages/message.js
- js-miniapp-sample/src/pages/uri-schemes.js
- js-miniapp-sample/src/routes.js
> feat: (sample) Replace mini app id with env variable

- js-miniapp-sdk/README.md
While camera is native and has no interface in the SDK, it still appears in the permissions. Explaining how to invoke and use it would facilitate it.
MINI-4887
> [MINI-4887] Added camera invoke documentation

- js-miniapp-sample/public/_locale/default/manifest.json
- js-miniapp-sample/public/_locale/ja/manifest.json
- js-miniapp-sample/public/manifest.json
Adding folder with localized manifests
> [NO-TICKET] Folder with localized manifests

- js-miniapp-bridge/package.json
- js-miniapp-sample/package.json
- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/package.json
**1.14.0** release-related changes
* Updated Changelog
* Updated release version numbers
* 
NOTE: Release will be done once the PRM is apporved.
> [PRM-1902] Release changes for 1.14.0

- .github/CONTRIBUTING.md
- .github/pull_request_template
This will simplify the PR template.
> docs: Move PR checklist to Contribution guide

- js-miniapp-sample/src/pages/file-download.js
- js-miniapp-sdk/CHANGELOG.md
* Updated Changelog
* Updated download page with new button - Filename with dot
> Updated Changelog and Refactor Download page with dot filename

- js-miniapp-sample/src/pages/event-listener.js
- js-miniapp-sample/src/pages/media.js
- js-miniapp-sample/src/pages/secure-storage.js
- js-miniapp-sample/src/pages/uri-schemes.js
- js-miniapp-sample/src/routes.js
* Changes for the Sample app that is needed for Secure Storage
[MINI-5201](https://jira.rakuten-it.com/jira/browse/MINI-5201)
> [MINI-5201] - Fix issues in sample app

- js-miniapp-sample/src/pages/file-download.js
- js-miniapp-sample/src/pages/secure-storage.js
* Fix for MINI-4939
* Removed QA Section from Sample app
MINI-4939
> JS Sample app fixes

- .github/CODEOWNERS
> [No Ticket] Updated Team

- js-miniapp-bridge/.nycrc
- js-miniapp-bridge/test/test.spec.ts
- js-miniapp-sdk/test/miniapp.spec.ts
Adding Unit Tests and Exclude Android and iOS directories as those are private APIs.
[MINI-4532](https://jira.rakuten-it.com/jira/browse/MINI-4532)
> [MINI-4532] Improve unit test code coverage percentage

- js-miniapp-bridge/src/common-bridge.ts
fix callbackId on bridge getMessagingUniqueId
[MINI-5636](https://jira.rakuten-it.com/jira/browse/MINI-5636)
> [MINI-5636] Use getMessagingUniqueid callback on getMessagingUniqueId

- js-miniapp-sample/src/pages/auth-token.js
- js-miniapp-sample/src/pages/secure-storage.js
* Updated Auth token error handling
[MINI-5706](https://jira.rakuten-it.com/jira/browse/MINI-5706)
[MALI-1211](https://jira.rakuten-it.com/jira/browse/MALI-1211)
> [MINI-5706][MALI-1211] Fix for Auth token issues

- js-miniapp-bridge/src/types/contact.ts
- js-miniapp-bridge/test/test.spec.ts
- js-miniapp-sample/src/pages/secure-storage.js
- js-miniapp-sample/src/pages/user-details.js
- js-miniapp-sdk/CHANGELOG.md
This PR aims to add the changes in JS SDK and sample app required to adopt multiple emails feature. Additionally, it's updating the **User Details** page in JS Sample app to be categorized in multiple tabs per feature e.g. Profile (User name, Photo), Contacts, Points. Please review the screenshots for reference. 
|  |  |
:-------------------------:|:-------------------------:
- MINI-5825
- MINI-5829
> [MINI-5825][MINI-5829] Supports multiple emails: SDK & JS Sample app changes

- js-miniapp-sample/src/components/ToolBar.js
- js-miniapp-sample/src/routes.js
Apply state on the toolbar.
MINI-5837
https://rak.box.com/s/pwybhchzn0smogtytv8ct1no4h0c5mmx
https://rak.box.com/s/zjktm76x68th9kabqgkwy38r4z4sqm54
> [MINI-5837] Apply state on toolbar

- js-miniapp-sample/src/pages/auth-token.js
- js-miniapp-sample/src/pages/user-details.js
* This fixes the Access token issue and User details page issue
[MINI-5858](https://jira.rakuten-it.com/jira/browse/MINI-5858)
> [MINI-5858] JS Sample app - Access token issue fix

- js-miniapp-sample/src/pages/in-app-purchase.js
- js-miniapp-sample/src/pages/user-details.js
- js-miniapp-sample/src/pages/web-location.js
* This PR aims to fix few issues in JS Sample app.
[MINI-6048](https://jira.rakuten-it.com/jira/browse/MINI-6048)
[MINI-6049](https://jira.rakuten-it.com/jira/browse/MINI-6049)
> [MINI-6048][MINI-6049] JS Sample app fixes

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-sample/package.json
- js-miniapp-sample/src/pages/landing.js
- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/src/modules/utils.ts
- package.json
* Added new interface in SDK to know if the device/app uses dark mode
[MINI-6132](https://jira.rakuten-it.com/jira/browse/MINI-6132)
> [MINI-6132] Fetch if the hostapp or device using Dark mode settings

- js-miniapp-sample/src/pages/file-download.js
- js-miniapp-sample/src/services/filedownload/actions.js
Updated the callback function  for the download file action in the sample app to throw the error to present in sample app UI.
[MALI-1050](https://jira.rakuten-it.com/jira/browse/MALI-1050)
> [MALI-1050] [JS Sample App] Infinite Loading is observed on downloading modified Base64 data

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-bridge/src/index.ts
- js-miniapp-bridge/src/types/analytics/analytics.ts
- js-miniapp-sample/src/pages/ads.js
- js-miniapp-sample/src/pages/app-close-alert.js
- js-miniapp-sample/src/pages/auth-token.js
- js-miniapp-sample/src/pages/camera.js
- js-miniapp-sample/src/pages/event-listener.js
- js-miniapp-sample/src/pages/file-download.js
- js-miniapp-sample/src/pages/file-upload.js
- js-miniapp-sample/src/pages/gifs.js
- js-miniapp-sample/src/pages/helper.js
- js-miniapp-sample/src/pages/in-app-purchase.js
- js-miniapp-sample/src/pages/landing.js
- js-miniapp-sample/src/pages/local-storage.js
- js-miniapp-sample/src/pages/media.js
- js-miniapp-sample/src/pages/message.js
- js-miniapp-sample/src/pages/secure-storage.js
- js-miniapp-sample/src/pages/share.js
- js-miniapp-sample/src/pages/universal-bridge.js
- js-miniapp-sample/src/pages/uri-schemes.js
- js-miniapp-sample/src/pages/user-details.js
- js-miniapp-sample/src/pages/uuid-sdk.js
- js-miniapp-sample/src/pages/web-location.js
- js-miniapp-sample/src/pages/window-actions.js
- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/src/index.ts
- js-miniapp-sdk/src/modules/utils.ts
This PR aims to add implementation on how to send Analytics to Host app
[MINI-6192](https://jira.rakuten-it.com/jira/browse/MINI-6192)
> [MINI-6192] Send Analytics to Host app

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-bridge/src/index.ts
- js-miniapp-bridge/src/types/universal-bridge.ts
- js-miniapp-sample/src/pages/universal-bridge.js
- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/README.md
- js-miniapp-sdk/src/index.ts
- js-miniapp-sdk/src/modules/universal-bridge.ts
* Added a new interface to Universalbridge that helps the miniapp to send more than just a string/json
[MINI-6180](https://jira.rakuten-it.com/jira/browse/MINI-6180)
> [MINI-6180] Added new interface to Universalbridge

- js-miniapp-sdk/src/modules/utils.ts
* Fixed the blank screen issue
> [No Ticket]Blank screen issue fix

- js-miniapp-bridge/package.json
- js-miniapp-sample/package.json
- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/package.json
* Changes related to `v1.18.0`
> [No Ticket] Release related changes

- js-miniapp-sample/src/pages/user-details.js
* Fix to display Username & profile pic
[MINI-6244](https://jira.rakuten-it.com/jira/browse/MINI-6244)
> [MINI-6244] Username & profile photo permissions

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-sdk/package.json
- js-miniapp-sdk/src/modules/decoder.ts
- js-miniapp-sdk/src/modules/user-info.ts
If any of the contact names is having any special characters like ' or '' , it would break the entire contact list. Hence, we are providing an option for the native app to send the encoded contact names with the updated interface
https://jira.rakuten-it.com/jira/browse/MALI-1382
> [MALI-1382] Contacts encoding

- js-miniapp-bridge/src/types/host-environment-info.ts
- js-miniapp-bridge/src/types/platform.ts
- js-miniapp-sample/src/pages/app-close-alert.js
- js-miniapp-sample/src/pages/landing.js
- js-miniapp-sdk/src/miniapp.ts
- js-miniapp-sdk/src/modules/bridge-info-converter.ts
Added more optional parameters to HostEnvironmentInfo
https://jira.rakuten-it.com/jira/browse/MALI-1401
> [MALI-1401] Added Build type and more info into HostEnvironmentInfo

- js-miniapp-sdk/src/modules/bridge-info-converter.ts
* Converting the build types to Uppercase
> [MALI-1401] Converting the build types to upper case

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-bridge/src/index.ts
- js-miniapp-bridge/src/notification-bridge.ts
- js-miniapp-bridge/src/types/notification/notification-info.ts
* Added new interfaces for managing notifications & badge numbers
https://jira.rakuten-it.com/jira/browse/MALI-1400
> [MALI-1400] Create interfaces for managing notifications and badge numbers

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-bridge/src/modules/miniapp-preferences.ts
- js-miniapp-sample/package.json
- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/README.md
- js-miniapp-sdk/src/modules/miniapp-preferences.ts
https://jira.rakuten-it.com/jira/browse/MALI-1408
> [MALI-1408] - MiniApp preferences feature

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-bridge/src/modules/notification-bridge.ts
- js-miniapp-sample/src/pages/miniapp-preferences.js
- js-miniapp-sample/src/routes.js
- js-miniapp-sdk/src/miniapp.ts
* Sample app changes for MiniApp Preference
https://jira.rakuten-it.com/jira/browse/MALI-1427
> [MALI-1427] Sample app changes to support MiniApp Preference feature

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-sample/src/pages/feature-list.js
- js-miniapp-sample/src/routes.js
- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/README.md
- js-miniapp-sdk/src/modules/utils.ts
* Added a new feature 'getFeatureList()' that will return list of features supported by the SDK and host app
https://jira.rakuten-it.com/jira/browse/MALI-1458
> [MALI-1458] Get feature list changes

- js-miniapp-bridge/src/types/analytics/analytics.ts
- js-miniapp-sample/src/App.js
- js-miniapp-sample/src/pages/analytics.js
- js-miniapp-sample/src/pages/auth-token.js
- js-miniapp-sample/src/pages/helper.js
- js-miniapp-sample/src/routes.js
* Updated MAAnalyticsInfo with more parameters like accountId, applicationID, etc.,
* Added new page for Analytics
> [No Ticket] Update SDK to send analytics with more parameters

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-bridge/test/test.spec.ts
- js-miniapp-sample/src/pages/landing.js
- js-miniapp-sdk/README.md
- js-miniapp-sdk/src/modules/user-info.ts
- js-miniapp-sdk/test/miniapp.spec.ts
* Added getPhoneNumber() interface
> [OAF-22254] Get Phone Number 

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-sample/src/pages/deeplink-support.js
- js-miniapp-sample/src/routes.js
- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/README.md
- js-miniapp-sdk/src/modules/utils.ts
* Added new interface for deeplink scheme validation for MiniApps
> [OAF-22448] Deeplink scheme validation support

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-bridge/src/modules/browser-manager.ts
- js-miniapp-bridge/src/modules/gallery-manager.ts
- js-miniapp-bridge/src/modules/userprofile-manager.ts
- js-miniapp-bridge/src/types/share-info.ts
- js-miniapp-sample/src/pages/landing.js
- js-miniapp-sdk/src/miniapp.ts
- js-miniapp-sdk/src/modules/user-info.ts
- js-miniapp-sdk/src/modules/utils.ts
> [OAF-23937] Update new interfaces for Browser, Gallery & update share feature

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-bridge/src/modules/webview-config-manager.ts
- js-miniapp-sample/src/pages/web-view-config.js
- js-miniapp-sample/src/routes.js
- js-miniapp-sdk/src/miniapp.ts
- js-miniapp-sdk/src/modules/webview-config-provider.ts
> [OAF-24047] Enable/Disable Navigation gestures

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-bridge/src/index.ts
- js-miniapp-bridge/src/types/e-sim.ts
- js-miniapp-bridge/test/test.spec.ts
- js-miniapp-sample/src/pages/e-sim.js
- js-miniapp-sample/src/routes.js
- js-miniapp-sdk/src/index.ts
- js-miniapp-sdk/src/miniapp.ts
- js-miniapp-sdk/src/modules/e-sim.ts
- js-miniapp-sdk/test/miniapp.spec.ts
Adding esim integration support
https://confluence.rakuten-it.com/confluence/display/ONEAPP/eSIM+onboarding+for+eCare
https://jira.rakuten-it.com/jira/browse/OAF-25145
> [OAF-25145] esim interfaces

- js-miniapp-sample/package.json
- js-miniapp-sample/src/pages/web-view-config.js
- js-miniapp-sample/src/store/web-view-config.js
- yarn.lock
Update state management to keep state on re-render
> [OAF-25777] Web View Config state fix

- js-miniapp-bridge/package.json
- js-miniapp-sample/package.json
- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/README.md
- js-miniapp-sdk/package.json
> [Release 1.24.0] updating release number, changelogs and docs

- js-miniapp-bridge/src/common-bridge.ts
- js-miniapp-bridge/src/modules/browser-manager.ts
- js-miniapp-bridge/src/types/browser-options.ts
- js-miniapp-sample/src/pages/uri-schemes.js
- js-miniapp-sdk/CHANGELOG.md
- js-miniapp-sdk/README.md
- js-miniapp-sdk/src/modules/utils.ts
> [OAF-24021] Launch Internal browser with options

- js-miniapp-bridge/src/modules/utility-manager.ts
- js-miniapp-bridge/test/test.spec.ts
- js-miniapp-sample/src/pages/launch-app-settings.js
- js-miniapp-sample/src/routes.js
- js-miniapp-sdk/src/miniapp.ts
- js-miniapp-sdk/src/modules/utils.ts
- js-miniapp-sdk/test/miniapp.spec.ts
Add Launch App Settings interface to bridge, sdk and create sample page
[OAF-26391](https://jira.rakuten-it.com/jira/browse/OAF-26391)
> OAF-26391 - add launch app settings interface
