.circleci/config.yml, js-miniapp-sdk/package.json
See https://circleci.com/docs/2.0/yarn/#caching.
Caching wasn't working correctly due to there no longer being a `packag-lock.json` file.
Also renamed the `check` NPM script to `lint` because `check` conflicts with one of Yarn's built-in comands.
=> ci: Add caching for Yarn and install via --frozen-lockfile

README.md, package.json, tsconfig.json
Module resolution wasn't working correctly when merging the changes for the sample app. See: https://www.typescriptlang.org/docs/handbook/module-resolution.html\#module-resolution-strategies
=> build: Use 'node' module resolution for TS compile

js-miniapp-sdk/package.json, js-miniapp-sdk/src/index.ts, tsconfig.json, yarn.lock
Also used Browserify's `--standalone` option to expose the the SDK on a `MiniApp` object (at `window.MiniApp`. I had to change the `export` in `index.ts` to make it available properly.
=> build: (sdk) Add bundling w/ browserify

.circleci/config.yml, js-miniapp-sdk/package.json
Publish to GitHub releases after deployment. After running the publishing job, a release will be created on GitHub Releases tab which has the 'miniapp.bundle.js' attached. This is using GitHub's Hub CLI tool: https://github.com/github/hub.
=> GitHub publish release

.circleci/config.yml, js-miniapp-bridge/.eslintrc.json, js-miniapp-bridge/package.json, js-miniapp-bridge/src/bridge.js
Some JS features were unsupported on older browsers. The bridge script was not working on Android 5 and 6 because the default install of Chrome is a very outdated version. This means our bridge script needs to use features which target ES5. This commit replaces arrow functions (=>) with normal functions and replaces 'Array.find' with 'Array.filter'. Also moved the 'module.exports' to an 'if' statement to avoid errors in the browser.
Also added CircleCI job for bridge and setup linting with recommended settings and using es5 to ensure we don't use unsupported features
=> (bridge) Fix for Android 5 & 6

docs/1.0/api/README.md, docs/1.0/api/index.md, docs/1.0/api/interfaces/miniapp.md, docs/1.0/api/modules/_miniapp_.md
There were some issues with the previously published docs because Github Pages won't render files that start with an underscore, so most of the API pages were showing 404. Also fixed the link to the parent page in the breadcrumbs
=> Fix docs for v1.0.0 on gh-pages

.circleci/config.yml, js-miniapp-sdk/scripts/docs.sh, js-miniapp-sdk/scripts/readme-redirect.md, js-miniapp-sdk/src/index.ts
- Publish docs as X.X without fix version. Docs should be published as X.X so if a new fix version is published, it will replace the documentation for the previous version. However, publishing a new minor version will still create new a docs version
-  Change typedoc to 'file' mode instead of 'module'. The module mode causes issues with Github pages because it uses underscores in the filenames i.e. '_index_.html'. Github pages treats files that start with an underscore as hidden, so these pages were showing as 404.
- Fix breadcrumb parent link. Typedoc generates the parent link as 'README.md', but we are using 'index.md'. Typedoc doesn't have any options to easily change this (except hiding breadcrumbs), so I've added a 'README.md' wh
ich just redirects to index.
=> Fixes for doc publishing from CI

js-miniapp-sample/src/components/GreyCard.js, js-miniapp-sample/src/pages/auth-token.js, js-miniapp-sample/src/pages/chatbot.js, js-miniapp-sample/src/pages/fetch-credentials.js, js-miniapp-sample/src/pages/landing.js, js-miniapp-sample/src/pages/local-storage.js, js-miniapp-sample/src/pages/tests/landing.test.js, js-miniapp-sample/src/pages/user-details.js, js-miniapp-sample/src/pages/uuid_sdk.js, js-miniapp-sample/src/pages/web_location.js, js-miniapp-sample/src/routes.js
Added a new landing page that shows: This is a Demo App of Mini App JS SDK
Added a new generic GreyCard component that can be extended using the same MaterialUI syntax
https://jira.rakuten-it.com/jira/browse/MINIBUILD-159
=> Add Landing Page for MiniApp Sample for Js-SDK

js-miniapp-sample/src/hooks/useGeoLocation.js, js-miniapp-sample/src/hooks/useGeoLocation.test.js, js-miniapp-sample/src/pages/tests/web_location.test.js, js-miniapp-sdk/README.md
The SDK has added a new feature for requesting location permissions from the host app. The user is able to revoke permissions at any time, so 'requestLocationPermissions' must be called every time before using location
=> feat: (sample) Add location permissions request

.circleci/config.yml
There was an incorrect path in the 'Publish Documentation' step when copying the docs from generated folder
=> ci: Fix documentation publishing

js-miniapp-bridge/src/common-bridge.ts
Add `requestCustomPermissions` function in `common-bridge.ts` to ask for the custom permissions from miniapps to Android, iOS or Native.
[MINI-959](https://jira.rakuten-it.com/jira/browse/MINI-959)
=> bridge: add custom permission function in common bridge

js-miniapp-bridge/src/common-bridge.ts, js-miniapp-bridge/test/test.spec.ts
The iOS/Android side returns a string so this must be first parsed before it can be used. 
Also did some refactoring of the bridge tests to reduce duplication.
MINI-1586
=> fix: (bridge) Parse json response on request permissions

js-miniapp-bridge/test/test.spec.ts
The test cases of custom permission pass but there is long error log warning. This PR solves that issue.
=> test: error handle for custom permission

js-miniapp-sample/package.json
The script will run everytime that the build script is run. Also deletes txt files as these are unsupported by the backend
=> build: (sample) Add script to create ZIP file of build assets

.circleci/config.yml, README.md
This is so we can test the JS Sample App as a website using the new SDK feature.
I'm a little bit sad about using the `gh-pages` branch for multiple purposes (hosting both docs and the sample app) - but I think this is the most simple and straightforward way of deploying. I guess it's just a disadvantage of using a mono-repo.
=> ci: Deploy sample app to gh-pages branch on master merge

js-miniapp-bridge/src/types/custom-permissions.ts, js-miniapp-sample/src/hooks/useGeoLocation.js, js-miniapp-sdk/CHANGELOG.md, js-miniapp-sdk/README.md, js-miniapp-sdk/src/miniapp.ts, js-miniapp-sdk/test/miniapp.spec.ts
- Add a custom permission type for `rakuten.miniapp.device.location`.
- We need to consider how this permission fits into the flow of the native device permission for LOCATION. This PR aims to request for the device location using `requestCustomPermissions` first before it will ask by `requestPermission`. It will add the solution inside sdk as default implementation instead of sample app.
- MINI-1956
=> feat: add location permission to custom permissions management

js-miniapp-bridge/package.json, js-miniapp-sdk/package.json, js-miniapp-sdk/scripts/docs.sh, js-miniapp-sdk/typedoc.json, yarn.lock
The name was showing up in typedocs as 'js-miniapp-bridge' and also it was showing the version number for js-miniapp-bridge instead of the version for js-miniapp-sdk. This is possibly a bug in typedocs where it's pulling this from an external module rather than the main module. The only fix I could find is to manually set the 'name' property and remove the version.
Also moved the typedoc options into a typedoc.json file
=> docs: Fix name appearing in generated typedocs

.circleci/config.yml
Sample app wasn't getting deployed becuase of a difference with the bash environment on CI (it requires folders to be copied using '*' to specificy all files in the folder).
Also added commands to delete the 'sample' folder first before copying - this ensures that old, unusd files get removed
MINI-2403
=> ci: Fix sample app deployment

js-miniapp-sample/external-webview/index.html, js-miniapp-sample/src/pages/home.js, js-miniapp-sample/src/pages/landing.js, js-miniapp-sample/src/pages/uri-schemes.js
This was done by updating `external-webview/index.html` to allow receiving parameters and also sending a "callback URL" to this page (the URL of the mini app).
On the external webview page, the user can also set parameters which will be returned to the JS SDK Sample App, and the sample app will display these parameters on the landing page.
=> External webview: allow parameters to be passed and received

js-miniapp-sdk/scripts/docs.sh
Keep publishable documents for CI release.
=> build: fix keep publishableDocs

js-miniapp-sample/src/hooks/useGeoLocation.js, js-miniapp-sample/src/pages/web-location.js, js-miniapp-sdk/CHANGELOG.md, js-miniapp-sdk/src/miniapp.ts, js-miniapp-sdk/test/miniapp.spec.ts
- fix: Location permission support for older iOS/Android SDK
- The Location custom permission doesn't exist on the iOS/Android SDK < 2.7.0, so requestLocationPermission was failing to request the device permission on those versions.
- fix: Reject promise when location custom permission is denied
- feat: (sample) Display error messages on location screen
MINI-2450
MINI-2479
=> Fixes for location permission request

.gitignore, js-miniapp-sample/src/pages/landing.js
Append characters starts with `#` in Paramteers in sample app.
- MINI-2504
=> bugfix: print parameters in sample app when the character starts with hash 

js-miniapp-sample/src/pages/landing.js
Sample app is truncating long parameter while displaying. We can break the word by this PR.
- MINI-2532
=> ui bugfix: sample app is showing truncated parameter list

js-miniapp-bridge/src/common-bridge.ts, js-miniapp-bridge/src/types/ad-types/index.ts, js-miniapp-bridge/test/test.spec.ts, js-miniapp-sample/src/pages/ads.js, js-miniapp-sdk/CHANGELOG.md, js-miniapp-sdk/README.md, js-miniapp-sdk/src/miniapp.ts, js-miniapp-sdk/test/miniapp.spec.ts
This PR is to show Banner ads in Mobile SDK requested from Mini apps
`showBannerAd` method is created in both bridge and js SDK to support to show banner ads.
Initially, the idea is to show banner ads at the bottom of the web view, as discussed in the corresponding ticket.
While designing the functions `SMART_BANNER ` was kept in consideration.
Further development is possible I guess with the use of Adaptive banners, where I think dimensions can be passed as an argument to load user-defined banner sizes.
Initial banner placement and size idea is below,
https://jira.rakuten-it.com/jira/browse/MINIBUILD-719
=> MINIBUILD-719/feat: display banner ads

js-miniapp-bridge/src/android/android-bridge.ts, js-miniapp-bridge/src/common-bridge.ts, js-miniapp-bridge/src/ios/ios-bridge.ts, js-miniapp-sample/external-webview/index.html, js-miniapp-sample/src/hooks/useGeoLocation.test.js
- Change the text to "param to send to mini app".
- Fix few typo issues 
- MINI-2589
=> fix few typo issues

js-miniapp-sample/external-webview/index.html, js-miniapp-sample/package.json, yarn.lock
This resolves the following security issues:
- [Dependabot alert](https://github.com/rakutentech/js-miniapp/security/dependabot/js-miniapp-sample/package.json/axios/open): security issue in Axios - updated to 0.21.1
- [Codeql alert](https://github.com/rakutentech/js-miniapp/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmaster): XSS vulnerability in external webview page
=> Security: resolve XSS and Axios issues in Sample App

.circleci/config.yml, README.md
- docs: Add code-cov badge to readme
- ci: Upload code coverage for js-miniapp-bridge
Also, I noticed that CI wasn't uploading coverage to the correct Code-Cov project, so we weren't getting any reports on `master`. I've fixed that so we should get reports on `master` now: https://app.codecov.io/gh/rakutentech/js-miniapp/branch/master
=> Code-cov updates

js-miniapp-sample/src/pages/file-upload.js
Having this capability is misleading as it's not possible to programmatically remove the file from the input. This was causing an issue where "deleting" the file would make it not possible to add the same file again. This was happening because the `setFile` function can only be called when input's `onChange` event occurs - but `onChange` doesn't get triggered if you select the same file which is already set to the input.
Also added the 'multiple' property to enable selecting multiple files.
MINI-3027
=> fix: (sample) Remove 'delete' capability from file upload screen

js-miniapp-bridge/src/common-bridge.ts, js-miniapp-sample/src/pages/message.js, js-miniapp-sdk/README.md, js-miniapp-sdk/src/modules/chat-service.ts, js-miniapp-sdk/test/miniapp.spec.ts
- Bridge/SDK: Support send message by contact id.
- Sample: 
Change the response context to retrieve contact id, not message id.
This PR does not have Sample app for Support send message by contact id.
MINI-2475
=> bridge & sdk: send message to specific contact

js-miniapp-sdk/CHANGELOG.md, js-miniapp-sdk/package.json
Update changelog and version for v1.8.0.
=> release: v1.8.0

js-miniapp-sample/src/pages/ads.js, js-miniapp-sample/src/pages/file-upload.js
The `.call` method is supposed to be passed the `this` context as the first parameter.
Also fixed a label issue on the "File Upload" screen - change "KB" to "Bytes".
=> fix: (sample) Changes to ad id inputs were not being saved to state

js-miniapp-sample/src/pages/uuid-sdk.js
Changed the layout so that it will allow a line break in the middle of the ID
MINI-1778
=> fix: (sample) Long unique ids were not fully visible

js-miniapp-sdk/scripts/docs.sh
This fixes an issue where the version name isn't displayed correctly in the dropdown  in the generated docs.
=> fix: (sdk) Add quotes around version in docs generation script

js-miniapp-sdk/scripts/docs.sh
This fixes an issue where the versions in the documentation displayed in the wrong order when the version is greater than X.10
MINI-3425
=> fix: (sdk) Add date to docs version file to fix list order

.github/CODEOWNERS
Use `miniapp-sdk` team as the codeowner for this repo. This should be easier to manage than updating the codeowners file
=> Update codeowners to use Mini App SDK team

js-miniapp-sample/src/pages/uri-schemes.js
This issue was causing a 404 screen to appear when trying to navigate back to the mini app from the external webview if you passed a fragment to the webview
MINI-4020
=> fix: (sample) Issue with parsing fragment in callback uri

js-miniapp-sample/src/pages/gifs.js
Gif page in the sample app was not scrollable.
MALI-698
=> fix: (sample) Gif page was not scrollable

js-miniapp-sample/src/pages/file-download.js
Default permission state changed to true to hide the error message on first load .
MINI-4291
=> Default permission state change

js-miniapp-sample/src/pages/uri-schemes.js
The deep link field can also be used to open any external website, so updated the title to reflect that. Also some small improvements to use react hooks for setting the field state and fixed an issue to prevent the webview from redirecting when the URL is empty.
=> sample:  Change label on deep link field

js-miniapp-sample/src/hooks/useGeoLocation.js, js-miniapp-sample/src/pages/web-location.js
On Android, there is currently a case where the location request can load indefinitely if the Location Services are disabled on the device. Added a timeout to handle this case.
MALI-898
=> feat: (sample) Add loading icon and timeout on location page

js-miniapp-sample/package.json, js-miniapp-sample/src/components/Drawer.js, js-miniapp-sample/src/pages/file-download-xhr.js, js-miniapp-sample/src/routes.js, yarn.lock
SDK versions 4.0.0 and below do not support the new download feature, so we need to show the old XHR download screen instead.
For `file-download-xhr.js` I just copied back the old cold we had for that screen.
MALI-942
=> feat: (sample) Show XHR download screen on SDK versions below 4.1.0

js-miniapp-sample/src/pages/file-download.js
The file download links were expired and couldn't be downloaded (404). 
Replaced them with valid links.
=> Expired File Download Links

js-miniapp-bridge/src/types/download-file-headers.ts, js-miniapp-sdk/src/miniapp.ts
Allow any key name in DownloadFileHeaders type
=> fix: Allow any key name in DownloadFileHeaders type

js-miniapp-bridge/src/common-bridge.ts, js-miniapp-bridge/src/index.ts, js-miniapp-bridge/src/types/secure-storage.ts, js-miniapp-bridge/test/test.spec.ts, js-miniapp-sample/src/pages/landing.js, js-miniapp-sample/src/services/landing/actions.js, js-miniapp-sample/src/services/landing/reducers.js, js-miniapp-sample/src/services/reducers.js, js-miniapp-sdk/src/event-types/index.ts, js-miniapp-sdk/src/index.ts, js-miniapp-sdk/src/modules/secure-storage.ts
The ready/error events are sent very early when the mini app starts, so the mini app sometimes calls the event listener after the event has already been received. To handle this case, I added a variable in the bridge to cache the state. Also changed the SDK interfaces to accept callback functions instead of Promises
=> fix: Secure storage ready/error events not received in some cases

js-miniapp-sample/src/pages/universal-bridge.js
Universal Bridge JS Sample app changes to handle response form Host app for Interface 1.
Issue:  The returned response from Host app for sendJsonToHostapp(info) api was showing alert, this impacts the interface-1 feature in iOS case.
Cause: response of sendJsonToHostapp() was handled as window.alert().
Fix: Changed to handle the response form host app sdk sendJsonToHostapp() api to be show as text label in the js-sample miniapp.
[MINI-5752](https://jira.rakuten-it.com/jira/browse/MINI-5752)
[Fix Demo Video](https://rak.box.com/s/okrxnquvz0ylj9yg1tn7fpysdn569ixi)
=> [MINI-5752] Universal Bridge JS Sample app changes

js-miniapp-sample/src/pages/file-download.js
Issue: When downloading sample.zip file, An error message is seen "not found; Failed to download the mini app."
cause: The url for the sample.zip file was invalid hence the issue.
Fix: Updating the sample.zip file download URL in the JS-Sample app file-download.js file.
[MALI-6198](https://jira.rakuten-it.com/jira/browse/MALI-6198)
=> [MALI-6198] [JS Sample App] Unable to download ".zip" file from Sample app

js-miniapp-bridge/src/common-bridge.ts
=> [MALI-1357] Manage special characters transmitted to the MiniApp

js-miniapp-sample/src/pages/user-details.js
Fixed issue in sample app when fetching contacts with permissions turned off.
[MALI-1434](https://jira.rakuten-it.com/jira/browse/MALI-1434)
=> [MALI-1434] [JS Sample App]Contacts getting fetched even when permission is denied

js-miniapp-bridge/src/common-bridge.ts, js-miniapp-sample/src/App.js, js-miniapp-sample/src/pages/landing.js, js-miniapp-sdk/CHANGELOG.md, js-miniapp-sdk/README.md, js-miniapp-sdk/src/modules/utils.ts
Implement the interface miniAppFinishedLoading() in the MiniApp JS SDK and js bridge.
This method should be used my the miniapps to notify the host app after it has finished loading.
=> [MiniAppSDK][JS] Implement the interface miniAppFinishedLoading() to notify host app.
